using System.Text.RegularExpressions;

namespace TechStrap.Tests.Shared;

/// <summary>
/// The CSS the build compiled into src/{app}/wwwroot/css/app.css (compressed, never committed), with a minimal rule reader:
/// enough to ask "what does the rule with this exact selector declare", which is all the token tests need.
/// </summary>
internal sealed partial class CompiledCss
{
    [GeneratedRegex(@"(?<selector>[^{}]+)\{(?<body>[^{}]*)\}")]
    private static partial Regex RulePattern();

    private readonly List<(string Selector, string Body)> _rules;

    [GeneratedRegex(@"/\*.*?\*/", RegexOptions.Singleline)]
    private static partial Regex CommentPattern();

    private CompiledCss(string text)
    {
        Text = CommentPattern().Replace(text, string.Empty);
        _rules = RulePattern().Matches(Text).Select(m => (m.Groups["selector"].Value.Trim(), m.Groups["body"].Value)).ToList();
    }

    public string Text { get; }

    public static CompiledCss Load(string app)
    {
        var path = RepositoryRoot.Combine("src", app, "wwwroot", "css", "app.css");
        File.Exists(path).ShouldBeTrue($"{path} should be generated by the build");
        return new CompiledCss(File.ReadAllText(path));
    }

    /// <summary>Every declaration of every rule whose selector is exactly <paramref name="selector"/> (Bootstrap and brand rules merged, last wins), colours normalised.</summary>
    public IReadOnlyDictionary<string, string> Declarations(string selector)
    {
        var declarations = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (ruleSelector, body) in _rules.Where(r => r.Selector == selector))
        {
            foreach (var declaration in body.Split(';', StringSplitOptions.RemoveEmptyEntries))
            {
                var colon = declaration.IndexOf(':', StringComparison.Ordinal);
                if (colon > 0)
                {
                    var value = declaration[(colon + 1)..].Trim();
                    declarations[declaration[..colon].Trim()] = CssColor.IsColour(value) ? CssColor.Normalize(value) : value;
                }
            }
        }

        return declarations;
    }
}
