using System.Text.RegularExpressions;

namespace TechStrap.Tests.Shared;

/// <summary>
/// The CSS the build compiled into src/{app}/wwwroot/css/app.css (compressed, never committed), with a minimal rule reader:
/// enough to ask "what does the rule with this exact selector declare", which is all the token tests need.
/// </summary>
internal sealed partial class CompiledCss
{
    [GeneratedRegex(@"(?<selector>[^{}]+)\{(?<body>[^{}]*)\}")]
    private static partial Regex RulePattern();

    [GeneratedRegex(@"@font-face\{(?<body>[^}]*)\}")]
    private static partial Regex FontFacePattern();

    [GeneratedRegex(@"(?<name>[a-z-]+):\s*(?<value>[^;]+)(;|$)")]
    private static partial Regex DeclarationPattern();

    private readonly List<(string Selector, string Body)> _rules;

    [GeneratedRegex(@"/\*.*?\*/", RegexOptions.Singleline)]
    private static partial Regex CommentPattern();

    private CompiledCss(string text)
    {
        Text = CommentPattern().Replace(text, string.Empty);
        _rules = RulePattern().Matches(Text).Select(m => (m.Groups["selector"].Value.Trim(), m.Groups["body"].Value)).ToList();
    }

    public string Text { get; }

    /// <summary>
    /// The rules inside every <c>@media</c> block whose condition is exactly <paramref name="condition"/> as the compiler wrote it, for example <c>(max-width: 767.98px)</c>
    /// (compressed output has no space after <c>@media</c>). Empty when there is no such block, so a test asserting on it fails loudly.
    /// </summary>
    public CompiledCss InMedia(string condition)
    {
        var opening = "@media" + condition + "{";
        var inner = new System.Text.StringBuilder();
        var from = 0;
        while ((from = Text.IndexOf(opening, from, StringComparison.Ordinal)) >= 0)
        {
            var start = from + opening.Length;
            var depth = 1;
            var i = start;
            while (i < Text.Length && depth > 0)
            {
                depth += Text[i] == '{' ? 1 : Text[i] == '}' ? -1 : 0;
                i++;
            }

            inner.Append(Text, start, i - start - 1).Append(' ');
            from = i;
        }

        return new CompiledCss(inner.ToString());
    }

    /// <summary>Everything except the <c>@media</c> blocks: the rules a screen of any size gets. The base rule a media block then overrides.</summary>
    public CompiledCss OutsideMedia()
    {
        var outside = new System.Text.StringBuilder();
        var i = 0;
        while (i < Text.Length)
        {
            if (string.CompareOrdinal(Text, i, "@media", 0, "@media".Length) != 0)
            {
                outside.Append(Text[i++]);
                continue;
            }

            // Skip the whole block: past its opening brace, then to the brace that closes it.
            var depth = 1;
            i = Text.IndexOf('{', i) + 1;
            while (i < Text.Length && depth > 0)
            {
                depth += Text[i] == '{' ? 1 : Text[i] == '}' ? -1 : 0;
                i++;
            }
        }

        return new CompiledCss(outside.ToString());
    }

    public static CompiledCss Load(string app)
    {
        var path = RepositoryRoot.Combine("src", app, "wwwroot", "css", "app.css");
        File.Exists(path).ShouldBeTrue($"{path} should be generated by the build");
        return new CompiledCss(File.ReadAllText(path));
    }

    /// <summary>Every @font-face block as a name to value map (font-family unquoted).</summary>
    public IReadOnlyList<IReadOnlyDictionary<string, string>> FontFaces() =>
        FontFacePattern().Matches(Text)
            .Select(face => (IReadOnlyDictionary<string, string>)DeclarationPattern().Matches(face.Groups["body"].Value)
                .ToDictionary(d => d.Groups["name"].Value, d => d.Groups["value"].Value.Trim().Trim('"')))
            .ToList();

    /// <summary>Every declaration of every rule whose selector is exactly <paramref name="selector"/> (Bootstrap and brand rules merged, last wins), colors normalized.</summary>
    public IReadOnlyDictionary<string, string> Declarations(string selector)
    {
        var declarations = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (ruleSelector, body) in _rules.Where(r => r.Selector == selector))
        {
            foreach (var declaration in body.Split(';', StringSplitOptions.RemoveEmptyEntries))
            {
                var colon = declaration.IndexOf(':', StringComparison.Ordinal);
                if (colon > 0)
                {
                    var value = declaration[(colon + 1)..].Trim();
                    declarations[declaration[..colon].Trim()] = CssColor.IsColour(value) ? CssColor.Normalize(value) : value;
                }
            }
        }

        return declarations;
    }
}
