BeforeAll {
    $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path
    $script:MigrationsDir = Join-Path $script:RepoRoot 'src/TechStrap.Infrastructure/Migrations'
    $script:SchemaDoc = Get-Content -LiteralPath (Join-Path $script:RepoRoot 'docs/architecture/05-SCHEMA.md') -Raw

    $snapshot = Get-Content -LiteralPath (Join-Path $script:MigrationsDir 'TechStrapDbContextModelSnapshot.cs') -Raw
    $script:ModelTables = [regex]::Matches($snapshot, 'b\.ToTable\("(?<name>[a-z_]+)"') |
        ForEach-Object { $_.Groups['name'].Value } | Sort-Object -Unique

    $diagram = [regex]::Match($script:SchemaDoc, '(?s)```mermaid\s+erDiagram(?<body>.*?)```').Groups['body'].Value
    $script:DiagramEntities = [regex]::Matches($diagram, '(?m)^\s{4}(?<name>[a-z_]+)\s*\{') |
        ForEach-Object { $_.Groups['name'].Value } | Sort-Object -Unique
}

Describe 'schema documentation' {
    It 'finds the tables in the model snapshot and the entities in the diagram' {
        $script:ModelTables.Count | Should -BeGreaterThan 10
        $script:DiagramEntities.Count | Should -BeGreaterThan 10
    }

    It 'draws every table that the migrations create, and nothing else' {
        $script:DiagramEntities | Should -Be $script:ModelTables
    }

    It 'is linked from the architecture document' {
        (Get-Content -LiteralPath (Join-Path $script:RepoRoot 'docs/architecture/02-ARCHITECTURE.md') -Raw) |
            Should -Match '\]\(05-SCHEMA\.md\)'
    }
}

Describe 'migrations are tool-generated' {
    It 'gives every migration a generated designer file with the migration attribute' {
        $migrations = Get-ChildItem -LiteralPath $script:MigrationsDir -Filter '*.cs' |
            Where-Object { $_.Name -match '^\d{14}_\w+\.cs$' -and $_.Name -notmatch '\.Designer\.cs$' }
        $migrations.Count | Should -BeGreaterThan 3
        foreach ($migration in $migrations) {
            $designer = Join-Path $script:MigrationsDir ($migration.BaseName + '.Designer.cs')
            Test-Path -LiteralPath $designer | Should -BeTrue -Because "$($migration.Name) needs the Designer file that dotnet ef generates"
            $text = Get-Content -LiteralPath $designer -Raw
            $text | Should -Match '// <auto-generated />'
            $text | Should -Match ('\[Migration\("' + [regex]::Escape($migration.BaseName) + '"\)\]')
        }
    }

    It 'creates the search vectors as stored generated columns, not through triggers' {
        $search = Get-ChildItem -LiteralPath $script:MigrationsDir -Filter '*AddSearchVectors.cs' | Where-Object { $_.Name -notmatch 'Designer' }
        $text = Get-Content -LiteralPath $search.FullName -Raw
        $text | Should -Match 'computedColumnSql:'
        $text | Should -Match 'stored: true'
        $text | Should -Match 'Npgsql:IndexMethod", "GIN"'
        $text | Should -Not -Match '(?i)CREATE\s+TRIGGER'
    }
}
