// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using TechStrap.Infrastructure.Persistence;

#nullable disable

namespace TechStrap.Infrastructure.Migrations
{
    [DbContext(typeof(TechStrapDbContext))]
    partial class TechStrapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AdminEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subject_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_admin_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_admin_events_occurred_at");

                    b.HasIndex("SubjectType", "SubjectId")
                        .HasDatabaseName("ix_admin_events_subject_type_subject_id");

                    b.ToTable("admin_events", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentNotificationPreferenceRecord", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("NotifyNewTicket")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_new_ticket");

                    b.HasKey("AgentId", "ProductId")
                        .HasName("pk_agent_notification_preferences");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_agent_notification_preferences_product_id");

                    b.ToTable("agent_notification_preferences", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oidc_subject");

                    b.Property<string>("PublicDisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("public_display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_agents_email");

                    b.HasIndex("OidcSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_oidc_subject");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AttachmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_attachments_message_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_attachments_ticket_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.EmailOutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to_address");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_email_outbox_created_at_when_dead_lettered")
                        .HasFilter("status = 'DeadLettered'");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("ix_email_outbox_locked_until_when_sending")
                        .HasFilter("status = 'Sending'");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_email_outbox_next_attempt_at_when_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_email_outbox_ticket_id");

                    b.HasIndex("Kind", "ToAddress", "CreatedAt")
                        .HasDatabaseName("ix_email_outbox_kind_to_address_created_at");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_email_outbox_created_at_when_finished")
                        .HasDatabaseName("ix_email_outbox_created_at_when_finished")
                        .HasFilter("status IN ('Sent','Discarded')");

                    b.ToTable("email_outbox", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.IntakeIdempotencyKeyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_intake_idempotency_keys");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_intake_idempotency_keys_created_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_intake_idempotency_keys_ticket_id");

                    b.HasIndex("ApiKeyId", "KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_idempotency_keys_api_key_id_key_hash");

                    b.ToTable("intake_idempotency_keys", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.KbArticleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', coalesce(body_markdown, '')), 'C')", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_kb_articles");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_kb_articles_author_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_kb_articles_category_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_kb_articles_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("ProductId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_articles_product_id_slug");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ProductId", "Slug"), false);

                    b.HasIndex("Status", "PublishedAt")
                        .HasDatabaseName("ix_kb_articles_status_published_at");

                    b.ToTable("kb_articles", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.KbCategoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_kb_categories");

                    b.HasIndex("ProductId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_categories_product_id_slug");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ProductId", "Slug"), false);

                    b.ToTable("kb_categories", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.MessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("author_type");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("in_reply_to");

                    b.Property<string>("MessageId")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("message_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(body, '')), 'B')", true);

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_messages_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_messages_ticket_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductApiKeyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_product_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_product_api_keys_key_hash");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_api_keys_product_id");

                    b.ToTable("product_api_keys", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_colour");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("from_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<bool>("ListedOnLanding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("listed_on_landing");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumberPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("number_prefix");

                    b.Property<string>("PortalHost")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("portal_host");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("reply_to");

                    b.Property<string>("Tagline")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("tagline");

                    b.Property<string>("UploadedLogo")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("uploaded_logo");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_products_key");

                    b.HasIndex("NumberPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_products_number_prefix");

                    b.HasIndex("PortalHost")
                        .IsUnique()
                        .HasDatabaseName("ix_products_portal_host");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_number");

                    b.HasKey("ProductId")
                        .HasName("pk_product_ticket_sequences");

                    b.ToTable("product_ticket_sequences", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.RequesterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<string>("ExternalUserRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_user_ref");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_requesters");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_requesters_email");

                    b.HasIndex("ExternalUserRef")
                        .HasDatabaseName("ix_requesters_external_user_ref");

                    b.ToTable("requesters", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TagRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("colour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketAccessTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_ticket_access_tokens");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_ticket_access_tokens_requester_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_access_tokens_token_hash");

                    b.HasIndex("TicketId", "RequesterId")
                        .HasDatabaseName("ix_ticket_access_tokens_ticket_id_requester_id");

                    b.ToTable("ticket_access_tokens", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketArticleRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("MessageId", "ArticleId")
                        .HasName("pk_ticket_articles");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_ticket_articles_article_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_articles_ticket_id");

                    b.ToTable("ticket_articles", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ticket_events");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_events_ticket_id_occurred_at");

                    b.ToTable("ticket_events", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<DateTimeOffset?>("FirstResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_at");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_spam");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<bool>("MetadataTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("metadata_trusted");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("number");

                    b.Property<Guid?>("ParentTicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_ticket_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(subject, '')), 'A')", true);

                    b.Property<DateTimeOffset?>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("ix_tickets_last_activity_at_when_spam")
                        .HasFilter("is_spam = true");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_number");

                    b.HasIndex("ParentTicketId")
                        .HasDatabaseName("ix_tickets_parent_ticket_id");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_tickets_requester_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_tickets_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SolvedAt")
                        .HasDatabaseName("ix_tickets_solved_at_when_solved")
                        .HasFilter("status = 'Solved'");

                    b.HasIndex("AssigneeId", "Status")
                        .HasDatabaseName("ix_tickets_assignee_id_status");

                    b.HasIndex("ProductId", "Status", "LastActivityAt")
                        .HasDatabaseName("ix_tickets_product_id_status_last_activity_at");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketTagRecord", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("TicketId", "TagId")
                        .HasName("pk_ticket_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_ticket_tags_tag_id");

                    b.ToTable("ticket_tags", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentNotificationPreferenceRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.AgentRecord", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_notification_preferences_agents_agent_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_notification_preferences_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AttachmentRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.MessageRecord", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_messages_message_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.IntakeIdempotencyKeyRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductApiKeyRecord", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intake_idempotency_keys_product_api_keys_api_key_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intake_idempotency_keys_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.KbArticleRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.AgentRecord", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kb_articles_agents_author_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.KbCategoryRecord", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kb_articles_kb_categories_category_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kb_articles_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.KbCategoryRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kb_categories_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.MessageRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductApiKeyRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_api_keys_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithOne()
                        .HasForeignKey("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_ticket_sequences_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketAccessTokenRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.RequesterRecord", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_access_tokens_requesters_requester_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_access_tokens_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketArticleRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.KbArticleRecord", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_articles_kb_articles_article_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.MessageRecord", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_articles_messages_message_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_articles_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketEventRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_events_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.AgentRecord", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_agents_assignee_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany()
                        .HasForeignKey("ParentTicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tickets_tickets_parent_ticket_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_products_product_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.RequesterRecord", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_requesters_requester_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketTagRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TagRecord", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_tags_tags_tag_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.TicketRecord", null)
                        .WithMany("Tags")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_tags_tickets_ticket_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TicketRecord", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
