// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechStrap.Infrastructure.Persistence;

#nullable disable

namespace TechStrap.Infrastructure.Migrations
{
    [DbContext(typeof(TechStrapDbContext))]
    partial class TechStrapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentNotificationPreferenceRecord", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<bool>("NotifyNewTicket")
                        .HasColumnType("boolean")
                        .HasColumnName("notify_new_ticket");

                    b.HasKey("AgentId", "ProductId")
                        .HasName("pk_agent_notification_preferences");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_agent_notification_preferences_product_id");

                    b.ToTable("agent_notification_preferences", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OidcSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oidc_subject");

                    b.Property<string>("PublicDisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("public_display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_agents_email");

                    b.HasIndex("OidcSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_oidc_subject");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductApiKeyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("key_prefix");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_product_api_keys");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_product_api_keys_key_hash");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_api_keys_product_id");

                    b.ToTable("product_api_keys", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentColour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("accent_colour");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("from_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("key");

                    b.Property<string>("Logo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NumberPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("number_prefix");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("reply_to");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_products_key");

                    b.HasIndex("NumberPrefix")
                        .IsUnique()
                        .HasDatabaseName("ix_products_number_prefix");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("next_number");

                    b.HasKey("ProductId")
                        .HasName("pk_product_ticket_sequences");

                    b.ToTable("product_ticket_sequences", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.RequesterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<string>("ExternalUserRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_user_ref");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_requesters");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_requesters_email");

                    b.HasIndex("ExternalUserRef")
                        .HasDatabaseName("ix_requesters_external_user_ref");

                    b.ToTable("requesters", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.TagRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("colour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.AgentNotificationPreferenceRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.AgentRecord", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_notification_preferences_agents_agent_id");

                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_notification_preferences_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductApiKeyRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_api_keys_products_product_id");
                });

            modelBuilder.Entity("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", b =>
                {
                    b.HasOne("TechStrap.Infrastructure.Persistence.Records.ProductRecord", null)
                        .WithOne()
                        .HasForeignKey("TechStrap.Infrastructure.Persistence.Records.ProductTicketSequenceRecord", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_ticket_sequences_products_product_id");
                });
#pragma warning restore 612, 618
        }
    }
}
