namespace TechStrap.Admin.Tests;

/// <summary>The build compiles Styles/app.scss (Bootstrap via libman) to wwwroot/css/app.css; it is never committed.</summary>
public sealed class StyleBuildTests
{
    [Fact]
    public void Compiled_css_exists_and_contains_bootstrap()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "TechStrap.slnx")))
        {
            directory = directory.Parent;
        }

        directory.ShouldNotBeNull();
        var cssPath = Path.Combine(directory.FullName, "src", "TechStrap.Admin", "wwwroot", "css", "app.css");

        File.Exists(cssPath).ShouldBeTrue($"{cssPath} should be generated by the build");
        File.ReadAllText(cssPath).ShouldContain("--bs-primary");
    }
}
