<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/TechStrap.Admin/TechStrap.Admin.csproj" />
    <ProjectReference Include="../../src/TechStrap.Contracts/TechStrap.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Shared/*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
